import { withConversationChoices } from './rush-dialogue.js';
// Fictional, simplified service-desk scenarios for the Rush Hour game.
// The engine shuffles action positions; patches leave the original request open.
export const TICKETS = [
  {
    id: 'dns-museum',
    category: 'NETWORK',
    title: 'The DNS museum',
    quote: "The portal is down for everyone. By everyone, I mean me, but I asked with confidence.",
    brief: "The recently moved staff portal times out on Nina’s laptop. Other websites still open.",
    investigations: [
      {
        id: "dns-other-device", kind: "question",
        label: "Can anyone else open the portal?",
        reply: "Theo can, on the same office Wi-Fi. He has declined my invitation to panic.",
        evidence: "Another laptop on the same network opens the portal successfully.",
      },
      {
        id: "dns-recent-change", kind: "question",
        label: "When did this last work?",
        reply: "Yesterday, before the portal move. My laptop slept through the launch party.",
        evidence: "The failure began after the portal changed address; this laptop stayed asleep during the move.",
      },
      {
        id: "dns-compare-answers", kind: "diagnostic",
        label: "Compare local and current DNS answers",
        reply: "Simulated DNS check complete. One answer belongs in a glass display case.",
        evidence: "This laptop’s cache returns the old portal IP; the configured DNS resolver returns the current IP.",
      },
    ],
    clue: 'Only this laptop resolves the portal to its old IP. Its local DNS cache still holds that address.',
    user: 'Nina · Operations',
    icon: '🌐',
    actions: [
      { label: 'Refresh the local DNS cache', kind: 'fix', outcome: 'Current address found. Museum closed.' },
      { label: 'Lend an approved spare laptop', kind: 'patch', outcome: 'Spare works. Please fix my own laptop.' },
      { label: 'Clear the portal cookies', kind: 'wrong', outcome: 'Fewer cookies. Same old address.' },
    ],
  },
  {
    id: 'monitor-voices',
    category: 'AUDIO',
    title: 'Meeting by monitor',
    quote: "My headset is broken. I can hear the meeting, but it appears to be happening inside my monitor.",
    brief: "Meeting audio is audible at the desk but not through Theo’s connected headset.",
    investigations: [
      {
        id: "audio-output-location", kind: "question",
        label: "Where is the sound coming from?",
        reply: "The monitor speakers. I leaned closer to investigate and accidentally became the meeting.",
        evidence: "Call audio is playing through the monitor, not the headset.",
      },
      {
        id: "audio-headset-test", kind: "question",
        label: "Does the headset sound test work?",
        reply: "Both ears play the little test tune. The headset has prepared a strong defense.",
        evidence: "The connected headset passes its own playback test.",
      },
      {
        id: "audio-selected-output", kind: "diagnostic",
        label: "Inspect the meeting audio output",
        reply: "Simulated audio routing check complete. The meeting chose the largest rectangle.",
        evidence: "The meeting output is set to HDMI Monitor; the working headset is available but not selected.",
      },
    ],
    clue: 'Audio output is HDMI Monitor. The connected headset passes its sound test.',
    user: 'Theo · Sales',
    icon: '🎧',
    actions: [
      { label: 'Select the headset output', kind: 'fix', outcome: 'Voices return to the correct ears.' },
      { label: 'Use speakers in the empty room', kind: 'patch', outcome: 'Audible here. I still need my headset.' },
      { label: 'Increase microphone gain', kind: 'wrong', outcome: 'Your voice gets louder. Theirs does not.' },
    ],
  },
  {
    id: 'camera-shutter',
    category: 'VIDEO',
    title: 'Webcam witness protection',
    quote: "The camera needs reinstalling. It sees darkness, which is also my current opinion of the demo.",
    brief: "The meeting detects Priya’s webcam and its indicator lights up, but the preview is black.",
    investigations: [
      {
        id: "camera-other-app", kind: "question",
        label: "Is the preview black in another app?",
        reply: "Yes, the camera app gets the same dramatic void. Very consistent branding.",
        evidence: "The black preview affects both the meeting app and the camera app.",
      },
      {
        id: "camera-lens-check", kind: "question",
        label: "Can you inspect the lens area?",
        reply: "There is a tiny slider over it. I thought that was the camera’s off-duty curtain.",
        evidence: "A physical slider is covering the webcam lens.",
      },
      {
        id: "camera-device-check", kind: "diagnostic",
        label: "Check webcam status and permissions",
        reply: "Simulated device check complete. The software has an alibi.",
        evidence: "The webcam is detected, enabled, and allowed in both apps; no device or permission error is reported.",
      },
    ],
    onsite: {
      location: "Design demo desk",
      reason: "Help locate and operate the webcam’s physical privacy shutter if needed.",
    },
    clue: 'The webcam is detected and enabled. Its physical privacy shutter is closed.',
    user: 'Priya · Design',
    icon: '📷',
    actions: [
      { label: 'Open the privacy shutter', kind: 'fix', outcome: 'Mystery guest identified.' },
      { label: 'Join with audio only for now', kind: 'patch', outcome: 'Present, but the demo still needs video.' },
      { label: 'Change the virtual background', kind: 'wrong', outcome: 'New scenery. Same closed shutter.' },
    ],
  },
  {
    id: 'wrong-monitor-input',
    category: 'DISPLAY',
    title: 'Wrong channel, no remote',
    quote: "The second screen lost the internet. It says “No signal,” which sounds like a networking confession.",
    brief: "Owen’s laptop screen works, while the external monitor is powered on and shows “No signal.”",
    investigations: [
      {
        id: "display-cable-port", kind: "question",
        label: "Which monitor port has the cable?",
        reply: "HDMI 2. The cable is firmly seated; I have given it the official worried look.",
        evidence: "The laptop’s display cable is connected to the monitor’s HDMI 2 port.",
      },
      {
        id: "display-input-menu", kind: "question",
        label: "What input does the monitor show?",
        reply: "HDMI 1. I assumed the numbers were more of a suggestion.",
        evidence: "The monitor’s input menu currently selects HDMI 1.",
      },
      {
        id: "display-output-check", kind: "diagnostic",
        label: "Check external display output",
        reply: "Simulated display check complete. The laptop is sending a picture into the correct cable.",
        evidence: "External display output is enabled; the connected HDMI 2 path is active, while the monitor is listening on HDMI 1.",
      },
    ],
    onsite: {
      location: "Finance desk",
      reason: "Help identify the connected cable port and use the monitor’s physical input controls.",
    },
    clue: 'The cable is connected to HDMI 2. The monitor input is set to HDMI 1.',
    user: 'Owen · Finance',
    icon: '🖥️',
    actions: [
      { label: 'Select HDMI 2 on the monitor', kind: 'fix', outcome: 'Negotiations successful. Picture restored.' },
      { label: 'Work on the laptop screen for now', kind: 'patch', outcome: 'Working, but I still need both screens.' },
      { label: 'Reconnect Wi-Fi', kind: 'wrong', outcome: 'The monitor remains unimpressed.' },
    ],
  },
  {
    id: 'numbers-as-text',
    category: 'SPREADSHEET',
    title: 'Creative accounting',
    quote: "The formula deleted our budget. The numbers are right there, standing suspiciously still.",
    brief: "Maya’s SUM formula returns zero even though the selected cells visibly contain numeric values.",
    investigations: [
      {
        id: "sheet-import-source", kind: "question",
        label: "Where did these values come from?",
        reply: "A report export, pasted this morning. It promised numbers and apparently delivered number-shaped objects.",
        evidence: "The affected values were imported from a text-based report.",
      },
      {
        id: "sheet-range-check", kind: "question",
        label: "Which cells does the formula include?",
        reply: "Exactly the three I expected. I checked twice, then blamed the moon for completeness.",
        evidence: "The SUM formula references the intended cells; the range is not empty or misplaced.",
      },
      {
        id: "sheet-value-types", kind: "diagnostic",
        label: "Inspect the affected cell types",
        reply: "Simulated cell inspection complete. The digits are wearing text badges.",
        evidence: "All three cells are flagged “Number stored as text”; the SUM formula itself has no error.",
      },
    ],
    clue: 'The SUM range contains numeric text. Each cell is flagged Number stored as text.',
    user: 'Maya · Planning',
    icon: '📊',
    actions: [
      { label: 'Convert the affected cells to numbers', kind: 'fix', outcome: 'Arithmetic rejoins the team.' },
      { label: 'Check this total with a calculator', kind: 'patch', outcome: 'Total found. My spreadsheet is still broken.' },
      { label: 'Add two decimal places', kind: 'wrong', outcome: 'Two decimal places of nothing.' },
    ],
  },
  {
    id: 'accidental-browser-zoom', workstream:'req',
    category: 'BROWSER',
    title: 'Website for giants',
    quote: "The website redesigned itself for a lighthouse. I did touch some keys, but surely that is unrelated.",
    brief: "One browser shows oversized text and a button pushed out of view. Leo wants the previous page size back.",
    investigations: [
      {
        id: "zoom-compare-apps", kind: "question",
        label: "Are other apps enlarged too?",
        reply: "No. My other browser looks normal. This one has ambitions to become a billboard.",
        evidence: "The enlargement is limited to this browser; the desktop and other browser look normal.",
      },
      {
        id: "zoom-user-intent", kind: "question",
        label: "Was the larger size intentional?",
        reply: "No. I was holding Ctrl and scrolling. The old size was comfortable; this is a jump scare.",
        evidence: "The size changed accidentally; the user wants the previous 100% size restored.",
      },
      {
        id: "zoom-inspect-setting", kind: "diagnostic",
        label: "Inspect this browser’s zoom level",
        reply: "Simulated browser check complete. The page has doubled its stage presence.",
        evidence: "This browser’s zoom is 200%; the previous working setting was 100%.",
      },
    ],
    clue: 'Browser zoom was accidentally changed to 200%. The user wants the previous 100% size.',
    user: 'Leo · Marketing',
    icon: '🔍',
    actions: [
      { label: 'Reset this browser to 100% zoom', kind: 'fix', outcome: 'Normal size. The button comes home.' },
      { label: 'Use the other browser at 100%', kind: 'patch', outcome: 'That works. Please fix my usual browser too.' },
      { label: 'Increase display brightness', kind: 'wrong', outcome: 'A brighter oversized problem.' },
    ],
  },
  {
    id: 'stale-saved-login',
    category: 'SIGN-IN',
    title: 'Password archaeology',
    quote: "The account is locked everywhere. Except the website. The website is being inconveniently successful.",
    brief: "Sam’s desktop app repeatedly fails sign-in after a password change, while the web app still works.",
    investigations: [
      {
        id: "login-current-web", kind: "question",
        label: "Does a fresh web sign-in work?",
        reply: "Yes, with my current password. I will not read it aloud, even for the dramatic reenactment.",
        evidence: "A fresh web sign-in with the current credentials succeeds; no password is shared with the desk.",
      },
      {
        id: "login-desktop-prompt", kind: "question",
        label: "Does the desktop app ask you again?",
        reply: "No, it just retries the saved sign-in. Very loyal to a password we have already retired.",
        evidence: "The desktop app reuses its saved login rather than requesting the current one.",
      },
      {
        id: "login-app-status", kind: "diagnostic",
        label: "Inspect the desktop sign-in status",
        reply: "Simulated authentication status check complete; credential values remain hidden.",
        evidence: "The desktop app reports a stale saved login after the password change; web authentication is healthy.",
      },
    ],
    clue: 'Web sign-in works with the current password. The desktop app keeps submitting its old saved login.',
    user: 'Sam · Projects',
    icon: '🔑',
    actions: [
      { label: 'Refresh the desktop app sign-in', kind: 'fix', outcome: 'Old login retired. Desktop app connected.' },
      { label: 'Use the web app temporarily', kind: 'patch', outcome: 'Web works. I still need desktop sync.' },
      { label: 'Change the default browser', kind: 'wrong', outcome: 'New browser. Same stale desktop login.' },
    ],
  },
  {
    id: 'four-pages-per-sheet', workstream:'req',
    category: 'PRINTING',
    title: 'Report for ants',
    quote: "The printer shrank the report. We ordered handouts, not a secret message for ants.",
    brief: "Jules gets four tiny document pages on each printed sheet, although the document looks normal on screen.",
    investigations: [
      {
        id: "print-document-size", kind: "question",
        label: "Is the document itself full-size?",
        reply: "Yes. On screen it is a perfectly respectable human document.",
        evidence: "The document’s page size and text are normal before printing.",
      },
      {
        id: "print-preview-layout", kind: "question",
        label: "What does print preview show?",
        reply: "Four little pages on one sheet. So the machine did submit a warning illustration.",
        evidence: "Print preview already shows the same four-page layout as the paper output.",
      },
      {
        id: "print-pages-setting", kind: "diagnostic",
        label: "Inspect the print layout settings",
        reply: "Simulated print setup check complete. The printer is following extremely compact instructions.",
        evidence: "The print dialog is set to 4 pages per sheet rather than 1 page per sheet.",
      },
    ],
    clue: 'The document looks normal on screen. Print preview shows 4 pages per sheet.',
    user: 'Jules · Training',
    icon: '🖨️',
    actions: [
      { label: 'Select one page per sheet', kind: 'fix', outcome: 'Human-readable again.' },
      { label: 'Read the PDF on screen for now', kind: 'patch', outcome: 'Readable. I still need full-size handouts.' },
      { label: 'Increase print darkness', kind: 'wrong', outcome: 'Darker text for the same ants.' },
    ],
  },
  {
    id: 'offscreen-window',
    category: 'DESKTOP',
    title: 'Window working remotely',
    quote: "The app crashed invisibly. Its taskbar icon is still here, collecting a salary.",
    brief: "Ada’s app appears open in the taskbar but no window is visible after leaving a two-screen desk.",
    investigations: [
      {
        id: "window-last-location", kind: "question",
        label: "Where was the window last visible?",
        reply: "On the second monitor before I unplugged. It may still be emotionally attached to that desk.",
        evidence: "The window was on the external display immediately before that display was disconnected.",
      },
      {
        id: "window-task-switcher", kind: "question",
        label: "Does it appear in the task switcher?",
        reply: "Yes, with my work in the thumbnail. Selecting it brings me a beautiful view of nothing.",
        evidence: "The app is still running and has a window; switching to it does not bring it onto the laptop screen.",
      },
      {
        id: "window-bounds-check", kind: "diagnostic",
        label: "Compare window and screen positions",
        reply: "Simulated window check complete. The app is attending a display that no longer exists.",
        evidence: "The window is positioned beyond the laptop screen bounds, in the disconnected second display’s former area.",
      },
    ],
    clue: 'The app window is still positioned on a second display that was just disconnected.',
    user: 'Ada · People Ops',
    icon: '🪟',
    actions: [
      { label: 'Move the window onto the laptop display', kind: 'fix', outcome: 'App returns from remote work.' },
      { label: 'Reconnect the second display briefly', kind: 'patch', outcome: 'Found it. I need it working away from this desk.' },
      { label: 'Change the desktop wallpaper', kind: 'wrong', outcome: 'Lovely view. Missing window.' },
    ],
  },
  {
    id: 'outbox-offline',
    category: 'EMAIL',
    title: 'Outbox holding pattern',
    quote: "The office internet is down. I have emailed everyone to warn them, which may contain a flaw.",
    brief: "Ben’s mail client holds messages in the outbox, while ordinary websites continue to load.",
    investigations: [
      {
        id: "mail-web-status", kind: "question",
        label: "Can you open mail in the browser?",
        reply: "Yes, webmail loads my inbox. The internet has requested that I withdraw my accusation.",
        evidence: "Webmail and other websites are reachable on the same computer.",
      },
      {
        id: "mail-status-bar", kind: "question",
        label: "What does the mail status bar say?",
        reply: "“Work Offline.” I believed that was encouragement to leave the office.",
        evidence: "The desktop mail client explicitly reports Work Offline.",
      },
      {
        id: "mail-connection-state", kind: "diagnostic",
        label: "Check the mail client connection state",
        reply: "Simulated mail check complete. The outbox is waiting for the client’s permission to connect.",
        evidence: "The network is healthy, but the client’s Work Offline mode is enabled and queued messages are unsent.",
      },
    ],
    clue: 'The network is healthy. The mail client explicitly shows Work Offline; messages remain in its outbox.',
    user: 'Ben · Facilities',
    icon: '📨',
    actions: [
      { label: 'Turn off Work Offline and send the queue', kind: 'fix', outcome: 'Queue cleared. Spokesperson reassigned.' },
      { label: 'Use webmail for the next message', kind: 'patch', outcome: 'Webmail works. My outbox is still stuck.' },
      { label: 'Sort the outbox newest first', kind: 'wrong', outcome: 'A better-organized queue to nowhere.' },
    ],
  },
  {
    id: 'surprise-jazz', workstream:'req',
    category: 'BROWSER',
    title: 'Mandatory surprise jazz',
    quote: "Someone installed a saxophone in my laptop. Please stop the lesson before it learns without me.",
    brief: "Music plays while Erin works in another tab. The open training lesson should be paused, not just quiet.",
    investigations: [
      {
        id: "jazz-tab-source", kind: "question",
        label: "Does any browser tab show sound?",
        reply: "The training tab has a speaker symbol. I thought it was announcing employee of the month.",
        evidence: "The browser marks the training tab as the audio source.",
      },
      {
        id: "jazz-playback-goal", kind: "question",
        label: "Should the lesson keep playing silently?",
        reply: "No, I need to come back to this exact section. My education cannot be delegated to the wallpaper.",
        evidence: "The user needs playback stopped at the current lesson position; muting alone would not meet that need.",
      },
      {
        id: "jazz-player-state", kind: "diagnostic",
        label: "Inspect the training video player",
        reply: "Simulated media check complete. The saxophone has been traced to an ordinary play button.",
        evidence: "The training tab’s video is actively playing, and its playback timer is advancing.",
      },
    ],
    clue: 'The training tab shows a speaker icon. Its video is playing and the user wants playback paused.',
    user: 'Erin · Support',
    icon: '🎷',
    actions: [
      { label: 'Pause the video in the training tab', kind: 'fix', outcome: 'The jazz committee adjourns.' },
      { label: 'Mute the tab temporarily', kind: 'patch', outcome: 'Quiet, but my lesson is still playing.' },
      { label: 'Lower the microphone level', kind: 'wrong', outcome: 'Jazz continues its solo.' },
    ],
  },
  {
    id: 'mouse-battery',
    category: 'HARDWARE',
    title: 'Mouse retirement notice',
    quote: "The laptop is frozen. The trackpad still works, but my mouse has issued a separate statement.",
    brief: "Kit’s wireless mouse has stopped responding during layout work; the laptop’s trackpad still moves the pointer.",
    investigations: [
      {
        id: "mouse-other-controls", kind: "question",
        label: "Can you work with the trackpad?",
        reply: "Yes. The laptop is fine. My carefully worded “total collapse” report may need editing.",
        evidence: "The laptop and pointer respond normally to the built-in trackpad.",
      },
      {
        id: "mouse-power-warning", kind: "question",
        label: "Did the mouse show a warning?",
        reply: "A battery warning yesterday. I granted it a motivational extension.",
        evidence: "The wireless mouse reported low battery before it stopped responding.",
      },
      {
        id: "mouse-battery-status", kind: "diagnostic",
        label: "Inspect the mouse power status",
        reply: "Simulated device status check complete. Motivation is not an AA power source.",
        evidence: "The wireless mouse reports a depleted AA battery; the laptop’s input system is operating normally.",
      },
    ],
    onsite: {
      location: "Creative layout desk",
      reason: "Provide a replacement AA battery and help fit it in the wireless mouse if needed.",
    },
    clue: 'The wireless mouse reports a depleted AA battery. The laptop trackpad works normally.',
    user: 'Kit · Creative',
    icon: '🖱️',
    actions: [
      { label: 'Replace the mouse battery', kind: 'fix', outcome: 'Retirement postponed. Cursor reporting for duty.' },
      { label: 'Use the laptop trackpad for now', kind: 'patch', outcome: 'Working, but I still need my mouse for layouts.' },
      { label: 'Increase double-click speed', kind: 'wrong', outcome: 'Still waiting for the first click.' },
    ],
  },
].map(withConversationChoices);
